# Default values for orca-chart umbrella chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  environment: dev
  datacenter: GL
  imageRegistry: your-registry.azurecr.io
  imagePullSecrets:
    - name: registry-secret
  storageClass: standard

# Component toggles
components:
  airflow:
    enabled: true
  spark:
    enabled: true
  postgresql:
    enabled: true
  redis:
    enabled: true

# PostgreSQL Configuration
postgresql:
  enabled: true
  auth:
    username: postgres_admin
    database: postgres
    existingSecret: postgres-secret
    secretKeys:
      adminPasswordKey: POSTGRES_PASSWORD
  primary:
    persistence:
      enabled: true
      size: 20Gi
      storageClass: standard
  metrics:
    enabled: true

# Airflow Configuration
airflow:
  enabled: true
  defaultAirflowRepository: your-registry.azurecr.io/airflow
  defaultAirflowTag: 2.8.1
  webserver:
    defaultUser:
      enabled: true
      role: Admin
      username: admin
      email: admin@your-domain.com
      firstName: Admin
      lastName: User
      password: airflow123
  data:
    metadataConnection:
      user: postgres_admin
      host: orca-chart-postgresql
      port: 5432
      db: airflow
      sslmode: prefer
  redis:
    enabled: false  # Use external Redis
  postgresql:
    enabled: false  # Use external PostgreSQL

# Spark Configuration
spark:
  enabled: true
  image:
    registry: your-registry.azurecr.io
    repository: spark
    tag: 3.5.0
  master:
    replicaCount: 1
  worker:
    replicaCount: 2
  zookeeper:
    enabled: false

# Redis Configuration (for Airflow Celery)
redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: standard

# Ingress Configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: airflow.local
      paths:
        - path: /
          pathType: Prefix
          service:
            name: airflow-webserver
            port: 8080

# Monitoring
monitoring:
  enabled: false
  prometheus:
    enabled: false
  grafana:
    enabled: false

# Security
security:
  networkPolicies:
    enabled: false
  podSecurityPolicy:
    enabled: false

# Resource Quotas
resourceQuotas:
  enabled: false

# OpenShift specific configurations
openshift:
  enabled: false
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000