# Default values for airflow
# This is a YAML-formatted file.

image:
  repository: apache/airflow
  tag: 2.8.1-python3.11
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# Airflow configuration
airflowHome: /opt/airflow
airflowUser: airflow
airflowGroup: airflow

# Webserver configuration
webserver:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Scheduler configuration
scheduler:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Worker configuration
worker:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow
    database: airflow

# Redis configuration
redis:
  enabled: true
  auth:
    enabled: false

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: airflow.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Persistence
persistence:
  enabled: true
  size: 8Gi
  storageClass: ""

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

# Pod security context
podSecurityContext:
  fsGroup: 1000

# Service account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}