# UAT Environment Values
global:
  environment: uat
  datacenter: GL
  imageRegistry: your-registry.azurecr.io
  imagePullSecrets:
    - name: registry-secret
  storageClass: premium
  
# PostgreSQL Configuration
postgresql:
  enabled: true
  host: "orca-chart-uat-gl-postgres.postgres.database.azure.com"
  port: 5432
  auth:
    username: postgres_admin
    existingSecret: postgres-secret
    secretKeys:
      adminPasswordKey: POSTGRES_PASSWORD
  databases:
    - airflow
    - spark
  
# Airflow Configuration
airflow:
  enabled: true
  replicaCount: 2
  image:
    repository: your-registry.azurecr.io/airflow
    tag: 2.8.1
    pullPolicy: IfNotPresent
  
  webserver:
    replicaCount: 2
    service:
      type: ClusterIP
      port: 8080
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  
  scheduler:
    replicaCount: 1
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  
  workers:
    replicaCount: 3
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  
  config:
    webserver:
      base_url: "https://airflow-uat.your-domain.com"
    core:
      executor: CeleryExecutor
      sql_alchemy_conn: postgresql://postgres_admin@orca-chart-uat-gl-postgres.postgres.database.azure.com:5432/airflow
    celery:
      broker_url: redis://redis:6379/0
      result_backend: db+postgresql://postgres_admin@orca-chart-uat-gl-postgres.postgres.database.azure.com:5432/airflow
  
  persistence:
    enabled: true
    size: 50Gi
    storageClass: premium
    
# Spark Configuration
spark:
  enabled: true
  image:
    repository: your-registry.azurecr.io/spark
    tag: 3.5.0
    pullPolicy: IfNotPresent
  
  master:
    replicaCount: 1
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 2Gi
  
  worker:
    replicaCount: 4
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 2Gi
  
  config:
    spark.sql.warehouse.dir: /opt/spark/spark-warehouse
    spark.sql.catalogImplementation: hive
    spark.sql.adaptive.enabled: true
    spark.sql.adaptive.coalescePartitions.enabled: true
    spark.sql.adaptive.coalescePartitions.minPartitionNum: 1
    
  persistence:
    enabled: true
    size: 100Gi
    storageClass: premium

# Redis Configuration (for Airflow Celery)
redis:
  enabled: true
  image:
    repository: redis
    tag: 7.0
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 6379
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  persistence:
    enabled: true
    size: 10Gi
    storageClass: premium

# Ingress Configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    - hosts:
        - airflow-uat.your-domain.com
        - spark-uat.your-domain.com
      secretName: orca-chart-uat-tls
  hosts:
    - host: airflow-uat.your-domain.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: airflow-webserver
            port: 8080
    - host: spark-uat.your-domain.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: spark-master
            port: 8080

# Monitoring
monitoring:
  enabled: true
  prometheus:
    enabled: true
    retention: 7d
  grafana:
    enabled: true
    adminPassword: UAT_Admin_Password_123

# Security
security:
  networkPolicies:
    enabled: true
  podSecurityPolicy:
    enabled: true
    
# Resource Quotas
resourceQuotas:
  enabled: true
  requests:
    cpu: 4000m
    memory: 8Gi
  limits:
    cpu: 8000m
    memory: 16Gi
  
# OpenShift specific configurations
openshift:
  enabled: true
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
  route:
    enabled: true
    host: airflow-uat.apps.your-openshift-cluster.com
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect